// Copyright (c) 2004-2010 Avencia, Inc.
// 
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
// 
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.

using System.Collections.Generic;

namespace Avencia.Open.DAO
{
    /// <summary>
    /// This interface defines the "insert" methods of FastDAO.
    /// </summary>
    /// <typeparam name="T">The type of object that can be written.</typeparam>
    public interface IFastDaoInserter<T> where T : new()
    {
        /// <summary>
        /// Inserts this object as a new record/row/line/etc. in the data source.
        /// </summary>
        /// <param name="obj">The object to write.</param>
        /// <param name="setGeneratedId">Update the object with its new ID if the ID was 
        ///                              autogenerated by the database.  Depending on the implementation,
        ///                              that may requires a query to retrieve the ID, and "most" of the 
        ///                              time you don't need the ID (you insert the object and then are
        ///                              done with it) so there is an advantage to not retrieving the ID
        ///                              if not necessary.  Not all data sources support retrieving a
        ///                              generated ID.
        ///                              If setGeneratedId is false, this ONLY sets the 
        ///                              object's ID field(s) IF the implementation of the auto-generation
        ///                              requires us to obtain the ID before writing to the data source.</param>
        void Insert(T obj, bool setGeneratedId);

        /// <summary>
        /// Same as calling Insert(obj, false);
        /// </summary>
        /// <param name="obj">The object to write.</param>
        void Insert(T obj);

        /// <summary>
        /// Inserts a bunch of records in one transaction, hopefully faster than
        /// separate calls to Insert().  Whether it is actually faster depends on
        /// the implementation.
        /// </summary>
        /// <param name="insertUs">List of objects to insert.</param>
        void Insert(IEnumerable<T> insertUs);
    }
}